spring:
  application:
    name: ProductManagementSystem
  datasource:
      url: jdbc:postgresql://localhost:5432/product_db
      username: postgres
      password: 412006
      driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
